<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<AssemblyName>aMogusManager</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>c_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>portable</DebugType>
	</PropertyGroup>

  <ItemGroup>
    <Compile Remove="DepotDownloader\**" />
    <Compile Remove="frontend\**" />
    <Compile Remove="installer\**" />
    <Compile Remove="Release\**" />
    <EmbeddedResource Remove="DepotDownloader\**" />
    <EmbeddedResource Remove="frontend\**" />
    <EmbeddedResource Remove="installer\**" />
    <EmbeddedResource Remove="Release\**" />
    <None Remove="installer\**" />
    <None Remove="Release\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SIPSorcery.WebSocketSharp" Version="0.0.1" />
    <PackageReference Include="SteamKit2" Version="3.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="DepotDownloader\DepotDownloader\DepotDownloader.csproj" />
  </ItemGroup>


  <ItemGroup>
    <None Update="amogusmanager-ui.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="icon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="version.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="versions.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
