<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<AssemblyName>mainApplication</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>c_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>portable</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>portable</DebugType>
	</PropertyGroup>

  <ItemGroup>
    <Compile Remove="aBootstrap\**" />
    <Compile Remove="aDownloader\**" />
    <Compile Remove="bootstrap\**" />
    <Compile Remove="DepotDownloader\**" />
    <Compile Remove="old\**" />
    <Compile Remove="Release\**" />
    <Compile Remove="test\**" />
    <EmbeddedResource Remove="aBootstrap\**" />
    <EmbeddedResource Remove="aDownloader\**" />
    <EmbeddedResource Remove="bootstrap\**" />
    <EmbeddedResource Remove="DepotDownloader\**" />
    <EmbeddedResource Remove="old\**" />
    <EmbeddedResource Remove="Release\**" />
    <EmbeddedResource Remove="test\**" />
    <None Remove="aBootstrap\**" />
    <None Remove="aDownloader\**" />
    <None Remove="bootstrap\**" />
    <None Remove="DepotDownloader\**" />
    <None Remove="old\**" />
    <None Remove="Release\**" />
    <None Remove="test\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SteamKit2" Version="3.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="aDownloader">
      <HintPath>aDownloader.dll</HintPath>
    </Reference>
    <Reference Include="DepotDownloader">
      <HintPath>DepotDownloader.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="icon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="version.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="versions.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
