<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	<AssemblyName>mainApplication</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>c_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Title>aMogusManager</Title>
    <SignAssembly>False</SignAssembly>
    <PublishAot>False</PublishAot>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <AllowUnsafeBlocks>False</AllowUnsafeBlocks>
    <PublishTrimmed>False</PublishTrimmed>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bootstrap\**" />
    <Compile Remove="old\**" />
    <EmbeddedResource Remove="bootstrap\**" />
    <EmbeddedResource Remove="old\**" />
    <None Remove="bootstrap\**" />
    <None Remove="old\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SteamKit2" Version="3.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DepotDownloader">
      <HintPath>DepotDownloader.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="version.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="versions.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
