<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>winexe</OutputType>
    <AssemblyName>aMogusManager</AssemblyName>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="aDownloader">
      <HintPath>..\aDownloader.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
